version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1993
      POSTGRES_DB: devdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dev-red

  php-app:
    build: .
    container_name: php-app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:80"
    networks:
      - dev-red

networks:
  dev-red:

volumes:
  postgres-data:
